### ISSUE TITLE
Capytaine Tutorial Issue

### ISSUE THREAD

**Issue by Chandler192** [capytaine/capytaine#223]
While following the capytaine tutorial I ran into an issue attempting to calculate the hydrostatics using the suggested line of hydrostatics = sphere.compute_hydrostatics(). I am operating out of anaconda3.8 and installed python and capytaine through said conda to ensure it was the latest version. When attempting to run the calculation, the following error occurs:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pickychicken192/anaconda3/envs/floatvawt/lib/python3.8/site-packages/capytaine/bodies/bodies.py", line 681, in compute_hydrostatics
    self.keep_immersed_part()
  File "/home/pickychicken192/anaconda3/envs/floatvawt/lib/python3.8/site-packages/capytaine/meshes/geometry.py", line 32, in enhanced_inplace_function
    inplace_function(object3d, *args, **kwargs)
  File "/home/pickychicken192/anaconda3/envs/floatvawt/lib/python3.8/site-packages/capytaine/bodies/bodies.py", line 971, in keep_immersed_part
    """Remove the parts of the mesh above the sea bottom and below the free surface."""
  File "/home/pickychicken192/anaconda3/envs/floatvawt/lib/python3.8/site-packages/capytaine/meshes/geometry.py", line 32, in enhanced_inplace_function
    inplace_function(object3d, *args, **kwargs)
  File "/home/pickychicken192/anaconda3/envs/floatvawt/lib/python3.8/site-packages/capytaine/bodies/bodies.py", line 959, in clip
    if len(ids) > 0:
TypeError: only integer scalar arrays can be converted to a scalar index

Any help you can offer with this error would be greatly appreciated.

**Comment by mancellin** [comment]
The tutorial and the code have just been updated just yesterday.
Could you double check that both are for version 1.4.2? (`from capytaine import __version__; print(__version__)`)

**Comment by mancellin** [comment]
If you are using conda, there is something like `conda update capytaine` which should update you to the latest version.
Your error message looks a lot like #206 which has been fixed in 1.4.2.

**Comment by mancellin** [comment]
@Chandler192 Did it solve your issue?

**Comment by Chandler192** [comment]
Yes sir. By uninstalling and reinstalling capytaine I was able to update it and the issue no longer messes with the code. Thank you very much for your help.
