### ISSUE TITLE
Problem trying to remove irregular frequencies with a lid

### ISSUE THREAD

**Issue by izabala123** [capytaine/capytaine#573]
Hi all

I would like to ask you for an example of the elimination of irregular frequencies using a lid. 
Using a working .py source code as a starting point, I've added 

`lid_mesh_1 = cpt.load_mesh("C:\\...\\mesh\\Body_1_lid.dat", file_format="nemoh")`

and `lid_mesh=lid_mesh_1,` to `cpt.FloatingBody`, but I get many errors.

Here I enclose you all the source and the errors. If necessary I can upload also the meshes.

Thank you!

```
import numpy as np
import capytaine as cpt
from capytaine.io.xarray import problems_from_dataset
from capytaine.bem.airy_waves import airy_waves_pressure
import xarray as xr
import os

mesh_1 = cpt.load_mesh("C:\\...\\mesh\\Body_1.dat", file_format="nemoh").immersed_part()
lid_mesh_1 = cpt.load_mesh("C:\\...\\mesh\\Body_1_lid.dat", file_format="nemoh")

body_1 = cpt.FloatingBody(mesh=mesh_1,lid_mesh=lid_mesh_1,  dofs=cpt.rigid_body_dofs(rotation_center=(0.0, 0.0, 0.0)), center_of_mass=(0.0, 0.0, 0.0), name="Body 1")

body_1.inertia_matrix = body_1.compute_rigid_body_inertia()
body_1.hydrostatic_stiffness = body_1.immersed_part().compute_hydrostatic_stiffness()

list_of_bodies = [body_1]
all_bodies = cpt.FloatingBody.join_bodies(*list_of_bodies).immersed_part()
test_matrix = xr.Dataset(coords={
    "omega": [0.1, 0.2, 0.3],
    "radiating_dof": list(all_bodies.dofs),
    "water_depth": 1000,
    "rho": 1025
})

solver = cpt.BEMSolver()
pbs = problems_from_dataset(test_matrix, all_bodies)
results = solver.solve_all(pbs, keep_details=True)
ds = cpt.assemble_dataset(results)

mesh = all_bodies.mesh

ds.coords["space_coordinate"] = ["x", "y", "z"]
ds["dof_definition"] = (["radiating_dof", "face", "space_coordinate"], np.array([all_bodies.dofs[dof] for dof in all_bodies.dofs]))

ds.coords["rigid_body_component"] = [body.name for body in list_of_bodies]
ds["rotation_center"] = (["rigid_body_component", "point_coordinates"], [body.rotation_center for body in list_of_bodies])
ds["center_of_mass"] = (["rigid_body_component", "point_coordinates"], [body.center_of_mass for body in list_of_bodies])

# Export to NetCDF file
from capytaine.io.xarray import separate_complex_values
separate_complex_values(ds).to_netcdf("KK.nc", encoding={"radiating_dof": {"dtype": "U"},
"influenced_dof": {"dtype": "U"}})
```

```
C:\...>call conda activate eBase
[14:42:06] WARNING  Inverting the direction of the normal vectors of Mesh(vertices=[[... 1188 vertices ...]],
                    faces=[[... 1190 faces ...]], name="C:\...\mesh\Body_1_lid.dat") to be downward.
           WARNING  Clipping C:\...\mesh\Body_1_lid.dat by Plane(normal=[0. 0.
                    1.], point=[0. 0. 0.]): all vertices are removed.
           WARNING  Clipping C:\...\mesh\Body_1_lid.dat by Plane(normal=[0. 0.
                    1.], point=[0. 0. 0.]): all vertices are removed.
Traceback (most recent call last):
  File "C:\...\KK.py", line 27, in <module>
    results = solver.solve_all(pbs, keep_details=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\miniforge3\envs\eBase\Lib\site-packages\capytaine\bem\solver.py", line 169, in solve_all
    self._check_wavelength_and_mesh_resolution(problems)
  File "C:\...\miniforge3\envs\eBase\Lib\site-packages\capytaine\bem\solver.py", line 195, in _check_wavelength_and_mesh_resolution
    risky_problems = [pb for pb in problems
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\miniforge3\envs\eBase\Lib\site-packages\capytaine\bem\solver.py", line 196, in <listcomp>
    if 0.0 < pb.wavelength < pb.body.minimal_computable_wavelength]
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\miniforge3\envs\eBase\Lib\site-packages\capytaine\bodies\bodies.py", line 1099, in minimal_computable_wavelength
    return max(8*self.mesh.faces_radiuses.max(), 8*self.lid_mesh.faces_radiuses.max())
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\miniforge3\envs\eBase\Lib\site-packages\capytaine\meshes\collections.py", line 179, in faces_radiuses
    return np.concatenate([mesh.faces_radiuses for mesh in self])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: need at least one array to concatenate
```

**Comment by mancellin** [comment]
Hi Iñaki,

So the issue is that somewhere a call to `immersed_part()` removes all panels in the `lid_mesh_1`, causing the ValueError you see.
Can you make sure that `lid_mesh_1` is on the free surface or below (z <= 0.0), but not even slightly above?
Otherwise, it is a bug on my side, and I could use a copy of your mesh to fix it.

Anyway, Capytaine should raise an error message sooner (and not just a warning) when the lid mesh is deleted.

**Comment by izabala123** [comment]
Hi Matthieu

The max value of z for `lid_mesh_1` is just 0.0. In fact, the example works perfectly, if I remove the code related with the lid, I mean, the line `lid_mesh_1 = cpt.load_mes
[mesh.zip](https://github.com/user-attachments/files/16247326/mesh.zip)
h("C:\\...\\mesh\\Body_1_lid.dat", file_format="nemoh")` and `lid_mesh=lid_mesh_1,` to `cpt.FloatingBody`.

Initially I tried the same example with the automatic lid generation, but it also failed with errors.

Here I enclose you the mesh files.

Thank you!
Iñaki

**Comment by mancellin** [comment]
So the code run if you remove the call to `immersed_part()` on the line
```python
all_bodies = cpt.FloatingBody.join_bodies(*list_of_bodies).immersed_part()
```

Now the bug is that this should not be removing the lid mesh :thinking:

**Comment by mancellin** [comment]
So if I merge the hull and lid mesh, then `immersed_part()` does not modify the mesh, the panels on the $z=0$ plane are kept:
```
(mesh_1 + lid_mesh_1).immersed_part().show()
```

But if I work on the lid mesh alone, then `immersed_part()` delete the panels on the $z=0$ plane:
```
print(lid_mesh_1.immersed_part().nb_faces)  # 0
```

**Comment by izabala123** [comment]
Hi Matthieu

That's right. The `immersed_part()` function was completely unnecessary, because the mesh was only of the immersed part. By removing `immersed_part()`, the simulation worked perfectly, with no complaints, and the results with lid are clearly better than without it. This is a good improvement.

Best regards
Iñaki
